### ISSUE TITLE
UnfiyLineEndingsInSolution causes files to be opened in external editor 

### ISSUE THREAD

**Issue by waynebloss** [jakubbielawa/LineEndingsUnifier#1]
Hi Jakub,

I'm wondering if we can have a separate setting to disable the call to `UnifyLineEndingsInSolution(false);` at [line 91](https://github.com/jakubbielawa/LineEndingsUnifier/blob/master/Line%20Endings%20Unifier/LineEndingsUnifierPackage.cs#L91) in `LineEndingsUnifierPackage.cs`?

Alternatively, could we make it only address open documents when one saves a solution?

I typically use the "SAVE-ALL" button in VS to save any *open* documents and to make sure that the `.sln` and `.csproj` files are saved...I never expected it to go into my un-opened files to change line endings. At first I did not realize it was doing this.

But now, I have set an external editor as the default editor for all of my JSON files and I noticed, as soon as I did this...whenever I hit "SAVE-ALL" in VS, all JSON files in my solution would open in the external editor. I suspected LineEndingsUnifier and disabled it, which confirmed my suspicion.

Do you experience this same behavior in the version of VS that you are using? I am on VS 2015 Pro.

If you tell me what course of action that you would like to take, I will be glad to send you a pull request. Thank you.

**Comment by jakubbielawa** [comment]
Hi Wayne,

I am experiencing the same behaviour on my VS. I use the VS 2015 Pro, too.
I've never thought about this - thank you for noticing it.

I think the best solution would be to introduce a new setting to disable/enable addressing only open documents after hitting the "Save All" button.

Thanks,
Jakub

**Comment by jakubbielawa** [comment]
Hi Wayne,

I've just uploaded an updated version with a new option - "Unify Only Open Files On Save All". I hope it solves this issue. Also, I'm very sorry for the delay.

Thanks,
Jakub

**Comment by waynebloss** [comment]
Hi @jakubbielawa 

No problem! Thank you so much for the free extension. Sorry that I couldn't help you earlier, I wanted to fix the problem myself but I didn't want to install an older version of VS to do it.

Thanks again!
