### ISSUE TITLE
Can't unify in solution/project/folder structure

### ISSUE THREAD

**Issue by MCvdBank** [jakubbielawa/LineEndingsUnifier#11]
Hi.
I currently have an issue with the management of inconsistent line endings in my project across multiple files. I found your plugin which seems to be exactly what I need, however I'm having difficulty with it.

I can't unify line endings for an entire solution (containing 2 projects) or per project. Whenever I select the unify option after right-clicking on any of the above items, nothing happens. The output window simply says `Unifying started...`. If I select a folder to unify, only the items in the first folder will be unified. It seems as if the extension is having difficulty with a complex folder structure where it can't traverse back to the parent folder after scanning its first child folder.

Please see the examples below:

Unify Line Endings In This **Project**
![image](https://cloud.githubusercontent.com/assets/5330234/26395176/939e6124-406f-11e7-8d20-e565cb0bef96.png)

Unify Line Endings In This **Folder**
![image](https://cloud.githubusercontent.com/assets/5330234/26395256/d01e0776-406f-11e7-8cd3-30eab527b60d.png)

I am using Visual Studio 2017, and the extension settings is configured as follows:
![image](https://cloud.githubusercontent.com/assets/5330234/26395422/37e846a0-4070-11e7-9ac6-8c403808843e.png)

Would you be able to assist with this issue?
Thank you.

**Comment by jakubbielawa** [comment]
Hi,

Unfortunately I can't reproduce the issue. 

Could you please give more details:
- What version of VS2017 are you using? (Community, Professional, Enterprise)
- Have you installed the latest VS2017 update?
- What other extensions do you use?
- Have you tried to reinstall the extension?
- Which version of the .NET Framework do you have installed on your computer?

The solution shown on the screenshots attached looks like some sample code. Could you please share it with me?

Thank you,
Jakub

**Comment by MCvdBank** [comment]
Hi,

- I have Visual Studio 2017 Community edition (on Windows 10)
- The newest update for VS is installed
- Please see the attached text file for a list of products and extensions. The only extensions that were not installed through the Visual Studio setup were JetBrains ReSharper, and Line Endings Unifier (both of which are up to date)
- I have tried to reinstall the extension, but to no avail
- The target framework is .NET 4.6.2

I created a brand new solution for the purposes of this issue. The only thing I added was a folder hierarchy with some example classes. In these, the "Custom" models have CRLF endings, and "Database" models have LF endings. You can find the zipped solution attached.

[VS_Info.txt](https://github.com/jakubbielawa/LineEndingsUnifier/files/1030901/VS_Info.txt)
[ExampleSolution.zip](https://github.com/jakubbielawa/LineEndingsUnifier/files/1030922/ExampleSolution.zip)

**Comment by jakubbielawa** [comment]
Unfortunately, I still can't reproduce the issue - even after installing the same extensions as you.
I can prepare a special version of Line Endings Unifier with some additional debug logging. Would you be willing to run such version on your computer and post the logs here?

**Comment by MCvdBank** [comment]
Yes, that is fine by me.

**Comment by jakubbielawa** [comment]
Hi, could you please run the attached version and post the logs here?

[LineEndingsUnifierWithLogging.zip](https://github.com/jakubbielawa/LineEndingsUnifier/files/1075505/LineEndingsUnifierWithLogging.zip)

**Comment by MCvdBank** [comment]
Hi, thank you for your support thus far! Below is the logging output of a few scenarios (for ExampleSolution.zip attached above):

Unify the "Models" folder:
[UnifyModelsFolder.txt](https://github.com/jakubbielawa/LineEndingsUnifier/files/1076626/UnifyModelsFolder.txt)

Unify the "Custom" folder:
[UnifyCustomFolder.txt](https://github.com/jakubbielawa/LineEndingsUnifier/files/1076627/UnifyCustomFolder.txt)

Unify the Project:
[UnifyProject.txt](https://github.com/jakubbielawa/LineEndingsUnifier/files/1076628/UnifyProject.txt)

Unify the Solution:
[UnifySolution.txt](https://github.com/jakubbielawa/LineEndingsUnifier/files/1076630/UnifySolution.txt)

The only operation that completed and displayed the success dialog was the flat "Custom" folder. Hopefully these logs are of some value to you.

**Comment by jakubbielawa** [comment]
Hi, thank you very much for the logs.

I've managed to finally reproduce the problem and fix the issue. The problem was that you had a trailing semicolon in your "Supported File Formats" list. Now everything should work correctly. 

Could you please run the attached version and let me know whether the issue is gone? Once you do it, I'll upload the updated version to the Marketplace.

[LineEndingsUnifierWithFix.zip](https://github.com/jakubbielawa/LineEndingsUnifier/files/1077726/LineEndingsUnifierWithFix.zip)

**Comment by MCvdBank** [comment]
Hi, 
It is working perfect now 😄
Thank you very much for your effort and support.

**Comment by jakubbielawa** [comment]
Thanks for the feeback and for using my extension.
