### ISSUE TITLE
Remove Spaces Issue

### ISSUE THREAD

**Issue by rjpeck2** [jakubbielawa/LineEndingsUnifier#12]
In version 1.8 if you have the remove spaces enabled and there's a small file with lot's of space the program adds some date to the end of the file. You can also make it happen by adding a lot of spaces to a small file and then saving it.

**Comment by jakubbielawa** [comment]
Hey, I created a small file with two lines - "hello world      " and one empty line. After that, I saved the file and a new line containing only three spaces appeared as a second line in the file - is that the bug you're talking about? Thanks.

**Comment by rjpeck2** [comment]
Let me know when you have a fix and I'll test it.

**Comment by jakubbielawa** [comment]
[LineEndingsUnifier_RemoveWhitespaceFix.zip](https://github.com/jakubbielawa/LineEndingsUnifier/files/1909574/LineEndingsUnifier_RemoveWhitespaceFix.zip)

Hey, could you please test this version and let me know if you still experience the issue?

**Comment by rjpeck2** [comment]
Looks good to me. It would be nice if in the next release you add an option to bypass the selection of the line endings each time the menu is selected.
.

**Comment by jakubbielawa** [comment]
Thanks. I'll open another issue for that idea and release the feature separately.
