### ISSUE TITLE
Support for VS2019

### ISSUE THREAD

**Issue by Ryan-rsm-McKenzie** [jakubbielawa/LineEndingsUnifier#18]
Any plans to support it? The community preview build is out now

**Comment by KimikoMuffin** [comment]
It would also be a good idea to set it up with [asynchronous autoloading](https://github.com/Microsoft/VSSDK-Extensibility-Samples/tree/master/AsyncPackageMigration) in the VS2019 version.

**Comment by Marat-Tanalin** [comment]
The stable version of Visual Studio 2019 has been released a month ago.

**Comment by jakubbielawa** [comment]
Hi guys, sorry it took such a long time. VS2019 is now supported. I'll open an issue for asynchronous autoloading.

**Comment by jdbenitezh** [comment]
thank you!!!!
