### ISSUE TITLE
In Visual Studio 2019, the editor says that it uses a deprecated API and then disables the extension

### ISSUE THREAD

**Issue by abelbraaksma** [jakubbielawa/LineEndingsUnifier#29]
After you install this extension to Visual Studio 2019 it complaints that the extension uses a deprecated API and can only be loaded if you enable synchronous loading of extensions. By default, it disables the extension.

I don't know what particular part of the API has been deprectated by Microsoft, but to enable this with asynchronous extension loading, I think the fix would be to get the deprecated code updated.

**Comment by abelbraaksma** [comment]
@jakubbielawa, is is possible for you to update your awesome extension to support this behavior? Since the change in policy at Microsoft, it is not possible anymore to use it, unless you use the non-recommended option to synchronously load all extensions, but that seriously adds to the overall start-up time.

I don't know if this is simple or hard, but I really love your extension, and now I really miss it since with VS2019 it cannot be used. If there's something I can do to help, please let me know.

More info on this policy and behavior:

* [Notification from Microsoft](https://devblogs.microsoft.com/visualstudio/updates-to-synchronous-autoload-of-extensions-in-visual-studio-2019/)
* [Migrate to AsyncPackage](https://devblogs.microsoft.com/visualstudio/updates-to-synchronous-autoload-of-extensions-in-visual-studio-2019/) for Marketplace

**Comment by MatthewT123** [comment]
While I agree an update would be great, I have also found that the extension does work in VS2019.  Doing so requires waiting for a banner to appear then accepting asynchronous autoload, restart, wait for banner, accept legacy API, restart, wait for banner, accept asynchronous autoload, restart (and possibly one more repeat, I lost count TBH).  Then it seems to work fine.

**Comment by abelbraaksma** [comment]
@MatthewT123, yes, using the deprecated api and synchronous load it works, but that shows down start up times significantly. The asynchronous feature requires an update as described by Microsoft.

**Comment by chasingcode** [comment]
Can the commit in the fork from @liulex be pulled in to fix this?
https://github.com/liulex/LineEndingsUnifier/commit/902c65f773a79d9a5ed393dc300bb917246ba229

**Comment by abelbraaksma** [comment]
@chasingcode, I've created a pull request. Hopefully @jakubbielawa can take a look. I didn't yet do a full test if the fix, hopefully it works. Cudos and thanks to @liulex for doing the heavy lifting here.

**Comment by abelbraaksma** [comment]
This is now solved. Tx!
