### ISSUE TITLE
Dockerfile and unsupported file format

### ISSUE THREAD

**Issue by Ekman** [jakubbielawa/LineEndingsUnifier#3]
Great plugin!

Running this on a Dockerfile produces the error:

> Error
>
> This is not a valid source file!

**Workaround:**

1. Rename Dockerfile to Dockerfile.txt file
2. Run the plugin on Dockerfile.txt
3. Rename Dockerfile.txt to Dockerfile

Would be awesome if it could be fixed!

**Comment by jakubbielawa** [comment]
Hi,

I'm glad you like it. I'll fix the issue and let you know.

Best,
Jakub

**Comment by Ekman** [comment]
Thank you!

**Comment by jakubbielawa** [comment]
I've just uploaded an updated version with a new option: Supported File Names which by default is set to "Dockerfile". It works on my machine. Could you please see if it works on yours?

**Comment by Ekman** [comment]
Works perfectly! Great job. Now I can use it with Docker.
