### ISSUE TITLE
"Force Default Line Ending On Document Save" conflicts with Typescript's "compileOnSave"

### ISSUE THREAD

**Issue by zugzwangm** [jakubbielawa/LineEndingsUnifier#5]
If you enable '**Force Default Line Ending On Document Save**', Typescript's '**compileOnSave**' (configured in tsconfig.json) stops working.

**Comment by jakubbielawa** [comment]
Thanks for the feedback. I'll look into it and fix the issue.

**Comment by jakubbielawa** [comment]
I've fixed the issue in the newest release. Thanks.
