### ISSUE TITLE
Visual Studio 2017 support?

### ISSUE THREAD

**Issue by jamespharvey20** [jakubbielawa/LineEndingsUnifier#6]
Would it be possible to update so Visual Studio 2017 is supported?  It's out as a release candidate, and quite a few extensions support it now.  I don't think there's be much to change.  I've never worked with VS extensions before, but simply trying to compile it on VS2017 fails.

**Comment by jakubbielawa** [comment]
I'll look into it and see if it's possible. Thanks.

**Comment by jakubbielawa** [comment]
I've just published an updated version of the extension with Visual Studio 2017 support. I'm sorry it took so long.
