### ISSUE TITLE
It will be disabled when restart Visual Studio 2105

### ISSUE THREAD

**Issue by Jin-Whu** [jakubbielawa/LineEndingsUnifier#7]
I have to enable it when I open Visual Studio 2015.

**Comment by Jin-Whu** [comment]
@jakubbielawa , I have to enable it every time when I start Visual Studio 2015. The LineEndingsUnifier version is 1.5

**Comment by jakubbielawa** [comment]
@Jin-Whu Hi, I did some research and this problem is connected with the Visual Studio MEF cache.
Have you tried to reinstall the extension? Some people have reported that they had to uninstall certain extensions twice (because somehow they got duplicated) and then install them again.

**Comment by Jin-Whu** [comment]
Thank you! I reinstall it. Not it can work!

**Comment by jakubbielawa** [comment]
@Jin-Whu Can I close the issue now?

**Comment by Jin-Whu** [comment]
Yes. Thank you for your reply.
