### ISSUE TITLE
Add option for line ending on last line?

### ISSUE THREAD

**Issue by jamespharvey20** [jakubbielawa/LineEndingsUnifier#9]
VS doesn't put a line ending on the last line, unless the user does.  Most other editors do, including vim, just hide it.  Some programs like git complain if there isn't a line ending on the last line.

It would be nice to have an option in your addon to put line endings on the last line, if that wouldn't be too difficult.

**Comment by jakubbielawa** [comment]
@jamespharvey20 Hi, sounds great! I will add such feature in the next release.

**Comment by jakubbielawa** [comment]
I've added such feature in the newest release. Thanks.
